{
    "$defs": {
        "chatMessage": {
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "format": "uuid"},
                "dialogUuid": {"type": "string", "format": "uuid"},
                "chatText": {"type": "string"},
                "userLanguage": {"type": "string"},
                "intentFocusedPrompt": {"type": "string"},
                "requestType": {"type": "string"},
                "createdAt": {"type": "string", "format": "date-time"},
            },
        },
        "stem": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "format": "str"},
                "mixId": {"type": "string", "format": "uuid"},
                "dialogUuid": {"type": "string", "format": "uuid"},
                "isOriginal": {"type": "boolean"},
                "isBlock": {"type": "boolean"},
                "title": {"type": "string"},
                "category": {"type": "string"},
                "packId": {"type": "string"},
                "sectionName": {"type": "string"},
                "songNumber": {"type": "number"},
                "barCount": {"type": "number"},
                "duration": {"type": "number"},
                "bpm": {"type": "number"},
                "key": {"type": "string"},
                "startPoint": {"type": "number"},
                "endPoint": {"type": "number"},
                "targetBpm": {"type": "number"},
                "targetKey": {"type": "string"},
                "keyDifference": {"type": "number"},
                "barOffset": {"type": "array", "items": {"type": "number"}},
                "uri": {"type": "string", "format": "uri"},
                "caption": {"type": "string"},
                "createAt": {"type": "string", "format": "date-time"},
                "chroma": {"type": "array", "items": {"type": "number"}},
                "gain": {"type": "number"},
                "loudness": {"type": "number"},
            },
        },
        "contextSongInfo": {
            "type": "object",
            "properties": {
                "song_id": {"type": "string"},
                "bpm": {"type": "number"},
                "key": {"type": "string"},
                "bar_count": {"type": "number"},
                "section_name": {"type": "string"},
                "section_role": {"type": "string"},
                "context_audio_uris": {
                    "type": "array",
                    "items": {"type": "string", "format": "uri"},
                },
                "generated_mix_uris": {
                    "type": "array",
                    "items": {"type": "string", "format": "uri"},
                },
            },
        },
        "promptStemInfo": {"type": "array", "items": {"$ref": "#/$defs/stem"}},
    },
    "title": "Request",
    "type": "object",
    "properties": {
        "request": [
            {
                "uuid": "string",
                "sessionUuid": "string",
                "taskId": "string",
                "speaker": "string",
                "dataType": "string",
                "turnIndex": "number",
                "thumb": "boolean",
                "status": "string",
                "tokenUsageId": ["string"],
                "requestUuid": "string",
                "processingTimeMs": "number",
                "schemaVersion": "string",
                "errorMessage": "string",
                "createdAt": "string",
                "updatedAt": "string",
                "medias": [
                    {
                        "id": "string",
                        "dialogUuid": "string",
                        "mediaType": "string",
                        "mediaName": "string",
                        "mediaPath": "string",
                        "caption": "string",
                        "createdAt": "string",
                    }
                ],
                "chatMessage": {
                    "uuid": "string",
                    "dialogUuid": "string",
                    "createdAt": "string",
                    "chatText": "string",
                    "intentFocusedPrompt": "string",
                },
                "context": {"previous_context": ["string"]},
                "requestInformation": {
                    "globalMusicInformation": None,
                    "stemPrompts": [
                        {"category": "string", "text": "string", "uri": "string"}
                    ],
                    "contextSongInfo": {
                        "songId": "string",
                        "bpm": "number",
                        "key": "string",
                        "barCount": "number",
                        "sectionName": "string",
                        "sectionRole": "string",
                        "contextAudioUris": ["string"],
                    },
                },
                "answers": [
                    {
                        "uuid": "string",
                        "sessionUuid": "string",
                        "taskId": "string",
                        "speaker": "string",
                        "dataType": "string",
                        "createdAt": "string",
                        "updatedAt": "string",
                        "turnIndex": "number",
                        "thumb": "boolean",
                        "status": "string",
                        "tokenUsageId": ["string"],
                        "requestUuid": "string",
                        "processingTimeMs": "number",
                        "schemaVersion": "string",
                        "errorMessage": "string",
                        "chatMessage": {
                            "uuid": "string",
                            "dialogUuid": "string",
                            "createdAt": "string",
                            "chatText": "string",
                            "intentFocusedPrompt": "string",
                        },
                        "mix": {
                            "mixData": {
                                "id": "string",
                                "dialogUuid": "string",
                                "status": "string",
                                "musicCaption": "string",
                                "title": "string",
                                "genre": ["string"],
                                "mood": ["string"],
                                "instruments": ["string"],
                                "duration": "number",
                                "bpm": "number",
                                "key": "string",
                                "startPoint": "number",
                                "endPoint": "number",
                                "audio_url": "string",
                                "thumbnail": "string",
                                "createdAt": "string",
                                "stems": [
                                    [
                                        {
                                            "id": "string",
                                            "mixId": "string",
                                            "dialogUuid": "string",
                                            "category": "string",
                                            "isOriginal": "boolean",
                                            "isBlock": "boolean",
                                            "sectionName": "string",
                                            "sectionRole": "string",
                                            "barCount": "number",
                                            "bpm": "number",
                                            "key": "number",
                                            "caption": "string",
                                            "uri": "string",
                                        }
                                    ]
                                ],
                            },
                            "suggestedStems": [
                                {
                                    "id": "string",
                                    "mixId": "string",
                                    "dialogUuid": "string",
                                    "category": "string",
                                    "isOriginal": "boolean",
                                    "isBlock": "boolean",
                                    "sectionName": "string",
                                    "sectionRole": "string",
                                    "barCount": "number",
                                    "bpm": "number",
                                    "key": "string",
                                    "caption": "string",
                                    "uri": "string",
                                }
                            ],
                        },
                    }
                ],
            },
        ],
    },
}
